# Generated by Django 3.2.5 on 2022-09-17 07:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('f&b', 'Food and Drinks'), ('accoms', 'Accomodations'), ('taxi', 'Taxi'), ('transport', 'Transportation'), ('flight', 'Flight tickets'), ('shopping', 'Shopping'), ('groceries', 'Groceries'), ('donatation', 'Donation'), ('entertainment', 'Entertainment'), ('auto', 'Auto and Parking'), ('bills', 'Bills'), ('fees', 'Fees'), ('health', 'Heath'), ('insurance', 'Insurance'), ('personalcare', 'Personal care')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('depart_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(related_name='trip_group', through='tracker.Group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trip')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trip'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('expense_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.expensetype')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('post', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trip')),
            ],
        ),
    ]
