# Generated by Django 3.2.5 on 2022-09-24 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.blog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('f&b', 'Food and Drinks'), ('accoms', 'Accomodations'), ('taxi', 'Taxi'), ('transport', 'Transportation'), ('flight', 'Flight tickets'), ('shopping', 'Shopping'), ('groceries', 'Groceries'), ('donatation', 'Donation'), ('entertainment', 'Entertainment'), ('auto', 'Auto and Parking'), ('bills', 'Bills'), ('fees', 'Fees'), ('health', 'Heath'), ('insurance', 'Insurance'), ('personalcare', 'Personal care')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ExpenseType',
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(related_name='comments_owned', through='tracker.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
