# Generated by Django 3.2.5 on 2022-09-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20220924_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
