# Generated by Django 3.2.5 on 2022-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20220924_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('Food and Drinks', 'Food and Drinks'), ('Accomodations', 'Accomodations'), ('Taxi', 'Taxi'), ('transport', 'Transportation'), ('Flight tickets', 'Flight tickets'), ('Shopping', 'Shopping'), ('Groceries', 'Groceries'), ('Donatation', 'Donation'), ('Entertainment', 'Entertainment'), ('Auto and Parking', 'Auto and Parking'), ('Bills', 'Bills'), ('Fees', 'Fees'), ('Health', 'Heath'), ('Insurance', 'Insurance'), ('Personalc Care', 'Personal care')], max_length=50),
        ),
    ]
